import { defineKnowledgeManifest } from '@content-automation/knowledge/registry/schema';

const outreachUses = ['research', 'qualification', 'outreach', 'citation', 'internal'] as const;

export const outreachKnowledgeManifest = defineKnowledgeManifest({
  moduleKey: 'outreach',
  version: 1,
  knowledge: 'contributes',
  entityTypes: [
    { key: 'outreach.account', name: 'Account', description: 'An organization viewed as a potential or current commercial account.', baseKind: 'organization', extends: 'core.organization', sensitivity: 'workspace', allowedUses: [...outreachUses] },
    { key: 'outreach.prospect', name: 'Prospect', description: 'A person viewed as a potential commercial contact.', baseKind: 'person', extends: 'core.person', sensitivity: 'restricted', allowedUses: [...outreachUses] },
    { key: 'outreach.message', name: 'Outreach message', description: 'A drafted or recorded outreach message.', baseKind: 'thing', extends: 'core.thing', sensitivity: 'restricted', allowedUses: ['outreach', 'internal'] },
    { key: 'outreach.observation', name: 'Research observation', description: 'A policy-specific observation derived from accepted claims.', baseKind: 'thing', extends: 'core.thing', sensitivity: 'restricted', allowedUses: ['research', 'qualification', 'outreach', 'internal'] },
    { key: 'outreach.insight', name: 'Prospect insight', description: 'A grounded relationship or commercial insight.', baseKind: 'thing', extends: 'core.thing', sensitivity: 'restricted', allowedUses: ['outreach', 'internal'] },
    { key: 'outreach.catalog_item', name: 'Catalog item', description: 'An offering or service that can be matched to account needs.', baseKind: 'thing', extends: 'core.thing', sensitivity: 'workspace', allowedUses: ['qualification', 'outreach', 'content', 'internal'] },
  ],
  predicates: [
    { key: 'outreach.prospect_at', name: 'Prospect at account', description: 'A prospect has a current or historical relationship with an account.', subjectTypes: ['outreach.prospect'], objectTypes: ['outreach.account'], objectKind: 'entity', sensitivity: 'restricted', allowedUses: [...outreachUses] },
    { key: 'outreach.observation_about', name: 'Observation about', description: 'An observation evaluates an account or prospect.', subjectTypes: ['outreach.observation'], objectTypes: ['outreach.account', 'outreach.prospect'], objectKind: 'entity', sensitivity: 'restricted', allowedUses: ['research', 'qualification', 'outreach', 'internal'] },
    { key: 'outreach.insight_about', name: 'Insight about', description: 'An insight concerns an account or prospect.', subjectTypes: ['outreach.insight'], objectTypes: ['outreach.account', 'outreach.prospect'], objectKind: 'entity', sensitivity: 'restricted', allowedUses: ['outreach', 'internal'] },
    { key: 'outreach.message_to', name: 'Message to', description: 'A message is intended for or records contact with a prospect.', subjectTypes: ['outreach.message'], objectTypes: ['outreach.prospect'], objectKind: 'entity', sensitivity: 'restricted', allowedUses: ['outreach', 'internal'] },
    { key: 'outreach.catalog_matches', name: 'Catalog matches', description: 'An offering matches an evidenced account need or opportunity.', subjectTypes: ['outreach.catalog_item'], objectTypes: ['outreach.account', 'core.concept'], objectKind: 'entity', sensitivity: 'workspace', allowedUses: ['qualification', 'outreach', 'content', 'internal'] },
  ],
  extractionProfiles: [
    { key: 'outreach.prospect_record', name: 'Prospect record', description: 'Project the current durable prospect record into shared knowledge.', entityTypes: ['outreach.prospect'], predicates: ['core.has_statement'], instructions: ['Treat the product record as authoritative for current prospect identity and status.', 'Do not infer facts beyond fields stored on the prospect record.'] },
    { key: 'outreach.account_research', name: 'Account research', description: 'Extract account facts and timing signals required by active ICP dimensions.', entityTypes: ['outreach.account', 'core.organization', 'core.person', 'core.concept', 'core.event', 'core.place'], predicates: ['core.about', 'core.mentions', 'core.related_to', 'core.has_statement'], instructions: ['Extract claims relevant to the active account dimensions.', 'Preserve dated timing signals, contradictions, and exact source spans.'] },
    { key: 'outreach.prospect_research', name: 'Prospect research', description: 'Extract person facts and relationships required by active persona dimensions.', entityTypes: ['outreach.prospect', 'outreach.account', 'core.person', 'core.organization', 'core.concept', 'core.event'], predicates: ['outreach.prospect_at', 'core.about', 'core.mentions', 'core.related_to', 'core.has_statement'], instructions: ['Extract only person-level claims relevant to active persona dimensions.', 'Do not copy company facts onto the person.'] },
    { key: 'outreach.relationship_intelligence', name: 'Relationship intelligence', description: 'Extract grounded relationship claims from notes, activities, messages, replies, and transcripts.', entityTypes: ['outreach.prospect', 'outreach.account', 'outreach.message', 'outreach.insight', 'core.event', 'core.concept'], predicates: ['outreach.prospect_at', 'outreach.message_to', 'outreach.insight_about', 'core.about', 'core.related_to', 'core.has_statement'], instructions: ['Attribute statements to their speaker or source.', 'Preserve disagreement and never treat generated outreach as recipient truth.'] },
  ],
  readProjections: [
    { key: 'outreach.account_assessment_context', name: 'Account assessment context', description: 'Claims used to evaluate ICP fit and timing.', entityTypes: ['outreach.account', 'core.organization', 'core.person', 'core.concept', 'core.event', 'core.place'], predicates: ['core.about', 'core.mentions', 'core.related_to', 'core.has_statement'], assessmentKinds: ['outreach.icp_assessment'], allowedUses: ['research', 'qualification', 'internal'], defaultLimit: 160 },
    { key: 'outreach.prospect_assessment_context', name: 'Prospect assessment context', description: 'Claims used to evaluate persona fit.', entityTypes: ['outreach.prospect', 'outreach.account', 'core.person', 'core.organization', 'core.concept', 'core.event'], predicates: ['outreach.prospect_at', 'core.about', 'core.mentions', 'core.related_to', 'core.has_statement'], assessmentKinds: ['outreach.persona_assessment'], allowedUses: ['research', 'qualification', 'internal'], defaultLimit: 120 },
    { key: 'outreach.prospect_intelligence_context', name: 'Prospect intelligence context', description: 'Relationship evidence for grounded prospect insights.', entityTypes: ['outreach.prospect', 'outreach.account', 'outreach.message', 'outreach.insight', 'core.event', 'core.concept'], predicates: ['outreach.prospect_at', 'outreach.message_to', 'outreach.insight_about', 'core.about', 'core.related_to', 'core.has_statement'], artifactKinds: ['outreach.insight', 'outreach.opportunity', 'outreach.message'], allowedUses: ['outreach', 'internal'], defaultLimit: 160 },
    { key: 'outreach.message_context', name: 'Outreach message context', description: 'Recipient-safe claims and account opportunities allowed to ground one message.', entityTypes: ['outreach.prospect', 'outreach.account', 'outreach.catalog_item', 'outreach.insight', 'core.organization', 'core.person', 'core.concept', 'core.event'], predicates: ['outreach.prospect_at', 'outreach.catalog_matches', 'outreach.insight_about', 'core.about', 'core.related_to', 'core.has_statement'], artifactKinds: ['outreach.insight', 'outreach.opportunity', 'outreach.message'], assessmentKinds: ['outreach.icp_assessment', 'outreach.persona_assessment'], allowedUses: ['outreach', 'citation'], defaultLimit: 80 },
  ],
  capabilityIds: ['outreach.account.get', 'outreach.prospect.get', 'outreach.prospect.research', 'outreach.account.research', 'outreach.prospect.qualify', 'outreach.insights.refresh', 'outreach.message.generate'],
  aliases: [],
  migrations: [],
});
