import sharp from "sharp";

export interface TextOverlayResult {
  bytes: Buffer;
  mimeType: "image/png";
  width: number;
  height: number;
}

export async function rasterizeImageForVision(input: {
  bytes: Buffer;
  mimeType: string;
}): Promise<{ bytes: Buffer; mimeType: string }> {
  if (input.mimeType !== "image/svg+xml") return input;
  return { bytes: await sharp(input.bytes).png().toBuffer(), mimeType: "image/png" };
}

function escapeXml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;",
  })[character]!);
}

function words(value: string, maxCharacters: number, maxLines: number): string[] {
  const tokens = value.replace(/\s+/g, " ").trim().split(" ").filter(Boolean);
  const lines: string[] = [];
  let current = "";
  for (const token of tokens) {
    const next = current ? `${current} ${token}` : token;
    if (next.length > maxCharacters && current) {
      lines.push(current);
      current = token;
      if (lines.length >= maxLines) break;
    } else current = next;
  }
  if (current && lines.length < maxLines) lines.push(current);
  if (tokens.join(" ").length > lines.join(" ").length && lines.length) {
    lines[lines.length - 1] = `${lines[lines.length - 1].replace(/[.,;:!?]?$/, "")}…`;
  }
  return lines;
}

function textLines(lines: string[], x: number, y: number, size: number, lineHeight: number): string {
  return `<text x="${x}" y="${y}" fill="#f8fafc" font-size="${size}" font-weight="760" text-anchor="start" font-family="Inter, ui-sans-serif, system-ui, sans-serif">${lines.map((line, index) => `<tspan x="${x}" dy="${index === 0 ? 0 : lineHeight}">${escapeXml(line)}</tspan>`).join("")}</text>`;
}

/**
 * Adds exact user copy to an image that has already been generated by the
 * configured provider. This is post-processing, never an image-generation
 * substitute or fallback.
 */
export async function applyExactTextOverlay(input: {
  bytes: Buffer;
  mimeType: string;
  text: string;
  width?: number;
  height?: number;
}): Promise<TextOverlayResult> {
  const width = input.width && input.width > 0 ? input.width : 1024;
  const height = input.height && input.height > 0 ? input.height : 1024;
  const fontSize = Math.max(30, Math.round(width * 0.055));
  const lineHeight = Math.round(fontSize * 1.2);
  const lines = words(input.text, width > height ? 34 : 25, 4);
  const firstBaseline = height - Math.round(height * 0.1) - (lines.length - 1) * lineHeight;
  const padding = Math.round(width * 0.065);
  const dataUrl = `data:${input.mimeType};base64,${input.bytes.toString("base64")}`;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${escapeXml(input.text)}">
  <image href="${dataUrl}" width="${width}" height="${height}" preserveAspectRatio="xMidYMid slice"/>
  <defs><linearGradient id="text-backdrop" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#000" stop-opacity="0"/><stop offset="1" stop-color="#000" stop-opacity=".88"/></linearGradient></defs>
  <rect x="0" y="${Math.round(height * 0.48)}" width="${width}" height="${Math.round(height * 0.52)}" fill="url(#text-backdrop)"/>
  ${textLines(lines, padding, firstBaseline, fontSize, lineHeight)}
</svg>`;
  return {
    bytes: await sharp(Buffer.from(svg)).png().toBuffer(),
    mimeType: "image/png",
    width,
    height,
  };
}
